using System.Globalization;
using System.Text;

namespace Gimnasy.Core.Shading;

/// <summary>Result of compiling a graph: the shader source plus diagnostics.</summary>
public sealed class ShaderCompileResult
{
    public required string FragmentSource { get; init; }
    public List<string> Errors { get; } = new();
    public List<string> Samplers { get; } = new();
    public bool Ok => Errors.Count == 0;
}

/// <summary>
/// Compiles a <see cref="ShaderGraph"/> into a GLSL fragment shader. It performs
/// a depth-first walk from the Output node, emitting one <c>vec4</c> temporary
/// per visited node in dependency order (with cycle protection), then writes the
/// PBR-ish output. This is what turns the visual node editor into a real shader.
/// </summary>
public static class ShaderGraphCompiler
{
    private static string Var(string id) =>
        "n_" + new string(id.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    private static string F(float v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static string Literal(float[] c) => c.Length switch
    {
        1 => $"vec4({F(c[0])})",
        2 => $"vec4({F(c[0])}, {F(c[1])}, 0.0, 0.0)",
        3 => $"vec4({F(c[0])}, {F(c[1])}, {F(c[2])}, 0.0)",
        _ => $"vec4({F(c[0])}, {F(c[1])}, {F(c[2])}, {F(c[3])})",
    };

    public static ShaderCompileResult Compile(ShaderGraph graph)
    {
        var errors = new List<string>();
        var statements = new List<string>();
        var emitted = new Dictionary<string, string>();
        var visiting = new HashSet<string>();

        string DefaultFor(string port) => port switch
        {
            "uv" => "vec4(v_uv, 0.0, 0.0)",
            "t" => "vec4(0.5)",
            "power" => "vec4(5.0)",
            _ => "vec4(0.0)",
        };

        string Resolve(string nodeId, string port)
        {
            var conn = graph.IncomingTo(nodeId, port);
            if (conn is not null) return Emit(conn.FromNode);
            var node = graph.Find(nodeId);
            if (node is not null && node.Params.TryGetValue(port, out var lit)) return Literal(lit);
            return DefaultFor(port);
        }

        string Emit(string nodeId)
        {
            if (emitted.TryGetValue(nodeId, out var existing)) return existing;
            if (!visiting.Add(nodeId))
            {
                errors.Add($"cycle detected at node '{nodeId}'");
                return "vec4(0.0)";
            }
            var node = graph.Find(nodeId);
            if (node is null) { errors.Add($"missing node '{nodeId}'"); visiting.Remove(nodeId); return "vec4(0.0)"; }
            if (!ShaderNodeLibrary.Defs.TryGetValue(node.Type, out var def))
            {
                errors.Add($"unknown node type '{node.Type}' (id={nodeId})");
                visiting.Remove(nodeId);
                return "vec4(0.0)";
            }

            var ins = new Dictionary<string, string>();
            foreach (var port in def.Inputs) ins[port] = Resolve(nodeId, port);

            string expr = def.Emit(ins, node);
            string var = Var(nodeId);
            statements.Add($"    vec4 {var} = {expr};");
            emitted[nodeId] = var;
            visiting.Remove(nodeId);
            return var;
        }

        // Walk from the output node.
        var output = graph.Nodes.Find(n => n.Type == "Output");
        if (output is null)
        {
            errors.Add("graph has no Output node");
            return new ShaderCompileResult { FragmentSource = "" }.With(errors);
        }

        string albedo = Resolve(output.Id, "albedo");
        string metallic = Resolve(output.Id, "metallic");
        string roughness = Resolve(output.Id, "roughness");
        string emission = Resolve(output.Id, "emission");
        string alpha = Resolve(output.Id, "alpha");

        var samplers = ShaderNodeLibrary.SamplerNodeIds(graph).Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("#version 330 core");
        sb.AppendLine("// Generated by Gimnasy ShaderGraphCompiler — do not edit by hand.");
        sb.AppendLine("in vec2 v_uv;");
        sb.AppendLine("in vec3 v_normal;");
        sb.AppendLine("in vec3 v_view;");
        sb.AppendLine("uniform float u_time;");
        foreach (var s in samplers) sb.AppendLine($"uniform sampler2D tex_{s};");
        sb.AppendLine("out vec4 FragColor;");
        sb.AppendLine();
        sb.AppendLine("void main() {");
        foreach (var line in statements) sb.AppendLine(line);
        sb.AppendLine($"    vec3 ALBEDO = ({albedo}).xyz;");
        sb.AppendLine($"    float METALLIC = ({metallic}).x;");
        sb.AppendLine($"    float ROUGHNESS = ({roughness}).x;");
        sb.AppendLine($"    vec3 EMISSION = ({emission}).xyz;");
        sb.AppendLine($"    float ALPHA = ({alpha}).x;");
        if (graph.Unshaded)
        {
            sb.AppendLine("    FragColor = vec4(ALBEDO + EMISSION, ALPHA);");
        }
        else
        {
            sb.AppendLine("    vec3 L = normalize(vec3(0.4, 0.8, 0.5));");
            sb.AppendLine("    float ndl = max(dot(normalize(v_normal), L), 0.0);");
            sb.AppendLine("    vec3 lit = ALBEDO * (0.25 + 0.75 * ndl) * (1.0 - 0.5 * METALLIC);");
            sb.AppendLine("    FragColor = vec4(lit + EMISSION, ALPHA);");
        }
        sb.AppendLine("}");

        var result = new ShaderCompileResult { FragmentSource = sb.ToString() };
        result.Errors.AddRange(errors);
        result.Samplers.AddRange(samplers);
        return result;
    }

    private static ShaderCompileResult With(this ShaderCompileResult r, List<string> errors)
    {
        r.Errors.AddRange(errors);
        return r;
    }
}
